// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swwioyolezbwhcsppzql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3d2lveW9sZXpid2hjc3BwenFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjA3NjYsImV4cCI6MjA2MTQ5Njc2Nn0.AgE7coRwAyYdM7_IU4HJRaJ6-7HHqMuvoW_AE_6PeH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);